apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-by8q
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-by8q
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-by8q
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-by8q
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-by8q
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wxjc-tenant/rhtap-demo-app/hacbs-test-project-by8q@sha256:ab28de799014fa4b441bfbbf864bbe775fce4da76f8c324e4efc80c55e2a8781
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
