apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-by8q
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wxjc-tenant/rhtap-demo-app/hacbs-test-project-by8q@sha256:ab28de799014fa4b441bfbbf864bbe775fce4da76f8c324e4efc80c55e2a8781
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
